export type LookupRelation = { id: number; name: string } | null;

export type Profile = {
  id: string;
  profileCreatedFor: string | null;
  firstName: string | null;
  lastName: string | null;
  gender: string | null;
  dateOfBirth: string | null;
  maritalStatus: string | null;
  numberOfChildren: number | null;
  childrenLivingWithYou: boolean | null;
  religionId: number | null;
  religion: LookupRelation;
  casteId: number | null;
  caste: LookupRelation;
  communityName: string | null;
  gothram: string | null;
  denominationId: number | null;
  denomination: LookupRelation;
  sect: string | null;
  motherTongueId: number | null;
  motherTongue: LookupRelation;
  knownLanguages: {
    languageId: number;
    language: { id: number; name: string };
  }[];
  communityPreference: string | null;
  timeOfBirth: string | null;
  placeOfBirth: string | null;
  rasiId: number | null;
  rasi: LookupRelation;
  nakshatraId: number | null;
  nakshatra: LookupRelation;
  lagna: string | null;
  dasaBhukti: string | null;
  chevvaiDosham: boolean | null;
  starCompatibility: string | null;
  education: string | null;
  degree: string | null;
  fieldOfStudy: string | null;
  collegeUniversity: string | null;
  occupation: string | null;
  jobTitle: string | null;
  companyName: string | null;
  industry: string | null;
  employmentType: string | null;
  annualIncome: string | null;
  workLocation: string | null;
  familyType: string | null;
  familyStatus: string | null;
  familyValues: string | null;
  fatherName: string | null;
  fatherOccupation: string | null;
  motherName: string | null;
  motherOccupation: string | null;
  numberOfBrothers: number | null;
  numberOfSisters: number | null;
  marriedSiblings: number | null;
  nativePlace: string | null;
  familyBackground: string | null;
  familyLocation: string | null;
  aboutFamily: string | null;
  ancestralOrigin: string | null;
  height: number | null;
  weight: string | null;
  bodyType: string | null;
  complexion: string | null;
  bloodGroup: string | null;
  physicalDisability: boolean | null;
  physicalDisabilityDetails: string | null;
  diet: string | null;
  smoking: string | null;
  drinking: string | null;
  fitnessLevel: string | null;
  hobbiesAndInterests: string | null;
  hobbies: string | null;
  interests: string | null;
  favouriteMusic: string | null;
  favouriteSports: string | null;
  favouriteReads: string | null;
  favouriteMovies: string | null;
  favouriteCuisine: string | null;
  cityId: number | null;
  city: LookupRelation;
  stateId: number | null;
  state: LookupRelation;
  countryId: number | null;
  country: LookupRelation;
  currentAddress: string | null;
  citizenship: string | null;
  residencyStatus: string | null;
  bio: string | null;
  photos: string[];
  primaryPhoto: string | null;
};

export type ProfileWithUser = Profile & {
  userId: string;
  user: { name: string; email: string };
};
